blank_issues_enabled: false
# List of issue forms to display
issue_forms:
  - name: "ğŸ› Bug Report"
    path: bug_report.yml
    description: "Report a bug or unexpected behavior in the application."
  - name: "âœ¨ Improve an Existing Feature"
    path: improve_feature.yml
    description: "Suggest an improvement for a feature that is already implemented."
  - name: "ğŸ’¡ Requests a Suggestion"
    path: suggestion.yml
    description: "Got an idea for a new feature or an improvement? We'd love to hear it!"