blank_issues_enabled: false
# List of issue forms to display
issue_forms:
  - name: "ğŸ› Bug Report"
    path: bug_report.yml
    description: "Report a bug or unexpected behavior in the application."
  - name: "âœ¨ Requests a Suggestion"
    path: suggestion.yml
    description: "Suggest an idea for a new feature or enhancement."